---
title: "Star_systems"
author: "Jinane AMAL"
format: html
editor: visual
---

```{r}
#| message: false
here::i_am("star_systems.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
library (stringr)
library(knitr)
library(readr)
```

You'll find [here](https://github.com/jinane1amal/star_systems.git) the link to my github sample test

## Question 3

```{r}
systems <- vroom("all-systems.csv")
str("all-systems.csv")
```

```{r}
# Check the number of star systems and variables
num_systems <- nrow(systems)
num_variables <- ncol(systems)
# Define columns with comma-separated values that need to be converted to numeric
comma_columns <- c( "Mass", "Star Luminosity", "relative radius")


numeric_columns <- c("STAR_KEY", "Distance (Lightyears)", "temperature", "Mass", "Star Luminosity", "relative radius")
numeric_verification <- sapply(systems[, numeric_columns, drop = FALSE], is.numeric)
numerical_check <- sapply(system, is.numeric)
all_numerical <- all(numerical_check)
if (num_systems == 1039 && num_variables == 8 && all_numerical) {
  cat("Data loaded successfully.")
} else {
  cat("Error: There is an issue with the loading process.")
}

# Display summary statistics
summary(systems)

```

## Question 4

```{r}

missing_values <- colSums(is.na(systems))
sum_missing_values <- sum(missing_values)

num_observations_with_missing <- sum(apply(systems, 1, anyNA))

summary_table <- data.frame(
  Metric = c("Number of Observations", "Number of Variables", "Number of Missing Values", "Number of Observations with Missing Values"),
  Value = c(num_systems, num_variables, sum(missing_values), num_observations_with_missing)
)

cat("| Metric | Value |\n")
cat("|--------|-------|\n")
cat(sprintf("| Number of Observations | %d |\n", num_systems))
cat(sprintf("| Number of Variables | %d |\n", num_variables))
cat(sprintf("| Number of Missing Values | %d |\n", sum_missing_values))
cat(sprintf("| Number of Observations with Missing Values | %d |\n", num_observations_with_missing))
knitr::kable(summary_table)
```

So, we have a situation where number of systems is `r num_systems` and the number of variables which we can observe is `r num_variables`. We thus have `r sum_missing_values ` missing values in the table in `r num_observations_with_missing` lines.

## Question 5

